import { PrismaClient } from '@prisma/client';
const p = new PrismaClient();

const todos = [
  ['Hipofisis / Hormonal','Cabergolina 0.5 mg'],['Hipofisis / Hormonal','Bromocriptina 2.5 mg'],
  ['Hipofisis / Hormonal','Octreotida 0.05 mg'],['Hipofisis / Hormonal','Octreotida 0.1 mg'],
  ['Hipofisis / Hormonal','Lanreotida 60 mg'],['Hipofisis / Hormonal','Lanreotida 90 mg'],
  ['Hipofisis / Hormonal','Lanreotida 120 mg'],['Hipofisis / Hormonal','Somatropina GH 4 UI'],
  ['Hipofisis / Hormonal','Somatropina GH 12 UI'],['Hipofisis / Hormonal','Desmopresina 0.1 mg'],
  ['Hipofisis / Hormonal','Desmopresina 0.2 mg'],
  ['Metabolismo Oseo','Calcio Vitamina D3 500/400'],['Metabolismo Oseo','Calcio Vitamina D3 1000/800'],
  ['Metabolismo Oseo','Vitamina D3 2000 UI'],['Metabolismo Oseo','Vitamina D3 5000 UI'],
  ['Metabolismo Oseo','Vitamina D3 50000 UI'],['Metabolismo Oseo','Alendronato 10 mg dia'],
  ['Metabolismo Oseo','Alendronato 70 mg semana'],['Metabolismo Oseo','Risedronato 35 mg semana'],
  ['Metabolismo Oseo','Ibandronato 150 mg mes'],['Metabolismo Oseo','Zoledronato 5 mg IV'],
  ['Metabolismo Oseo','Denosumab 60 mg SC'],['Metabolismo Oseo','Raloxifeno 60 mg'],
  ['Metabolismo Oseo','Teriparatida 20 mcg SC'],
  ['Obesidad / Sobrepeso','Orlistat 120 mg'],['Obesidad / Sobrepeso','Naltrexona Bupropion 8/90 mg'],
  ['Obesidad / Sobrepeso','Liraglutida 3 mg obesidad'],['Obesidad / Sobrepeso','Semaglutida 2.4 mg SC semanal'],
  ['Obesidad / Sobrepeso','Tirzepatida 5 mg semanal'],['Obesidad / Sobrepeso','Tirzepatida 10 mg semanal'],
  ['Obesidad / Sobrepeso','Tirzepatida 15 mg semanal'],
  ['Hormonas Sexuales','Testosterona cipionato 200 mg IM'],['Hormonas Sexuales','Testosterona undecanoato 40 mg VO'],
  ['Hormonas Sexuales','Testosterona gel 1%'],['Hormonas Sexuales','Estradiol 1 mg'],
  ['Hormonas Sexuales','Estradiol 2 mg'],['Hormonas Sexuales','Estradiol gel 0.1%'],
  ['Hormonas Sexuales','Progesterona 100 mg'],['Hormonas Sexuales','Progesterona 200 mg'],
  ['Hormonas Sexuales','Estrogenos conjugados 0.625 mg'],['Hormonas Sexuales','Tibolona 2.5 mg'],
  ['Antihipertensivos - IECA','Enalapril 5 mg'],['Antihipertensivos - IECA','Enalapril 10 mg'],
  ['Antihipertensivos - IECA','Enalapril 20 mg'],['Antihipertensivos - IECA','Lisinopril 5 mg'],
  ['Antihipertensivos - IECA','Lisinopril 10 mg'],['Antihipertensivos - IECA','Lisinopril 20 mg'],
  ['Antihipertensivos - IECA','Ramipril 2.5 mg'],['Antihipertensivos - IECA','Ramipril 5 mg'],
  ['Antihipertensivos - IECA','Ramipril 10 mg'],['Antihipertensivos - IECA','Perindopril 4 mg'],
  ['Antihipertensivos - IECA','Perindopril 8 mg'],
  ['Antihipertensivos - ARA II','Losartan 25 mg'],['Antihipertensivos - ARA II','Losartan 50 mg'],
  ['Antihipertensivos - ARA II','Losartan 100 mg'],['Antihipertensivos - ARA II','Valsartan 80 mg'],
  ['Antihipertensivos - ARA II','Valsartan 160 mg'],['Antihipertensivos - ARA II','Irbesartan 150 mg'],
  ['Antihipertensivos - ARA II','Irbesartan 300 mg'],['Antihipertensivos - ARA II','Telmisartan 40 mg'],
  ['Antihipertensivos - ARA II','Telmisartan 80 mg'],['Antihipertensivos - ARA II','Candesartan 8 mg'],
  ['Antihipertensivos - ARA II','Candesartan 16 mg'],['Antihipertensivos - ARA II','Olmesartan 20 mg'],
  ['Antihipertensivos - ARA II','Olmesartan 40 mg'],
  ['Antihipertensivos - Calcioantagonistas','Amlodipina 5 mg'],['Antihipertensivos - Calcioantagonistas','Amlodipina 10 mg'],
  ['Antihipertensivos - Calcioantagonistas','Nifedipina 10 mg'],['Antihipertensivos - Calcioantagonistas','Nifedipina OROS 30 mg'],
  ['Antihipertensivos - Calcioantagonistas','Nifedipina OROS 60 mg'],['Antihipertensivos - Calcioantagonistas','Diltiazem 60 mg'],
  ['Antihipertensivos - Calcioantagonistas','Diltiazem 120 mg'],['Antihipertensivos - Calcioantagonistas','Verapamilo 80 mg'],
  ['Antihipertensivos - Calcioantagonistas','Verapamilo 120 mg'],
  ['Antihipertensivos - Betabloqueantes','Atenolol 25 mg'],['Antihipertensivos - Betabloqueantes','Atenolol 50 mg'],
  ['Antihipertensivos - Betabloqueantes','Bisoprolol 2.5 mg'],['Antihipertensivos - Betabloqueantes','Bisoprolol 5 mg'],
  ['Antihipertensivos - Betabloqueantes','Bisoprolol 10 mg'],['Antihipertensivos - Betabloqueantes','Carvedilol 6.25 mg'],
  ['Antihipertensivos - Betabloqueantes','Carvedilol 12.5 mg'],['Antihipertensivos - Betabloqueantes','Carvedilol 25 mg'],
  ['Antihipertensivos - Betabloqueantes','Nebivolol 5 mg'],['Antihipertensivos - Betabloqueantes','Propranolol 40 mg'],
  ['Antihipertensivos - Betabloqueantes','Metoprolol 50 mg'],['Antihipertensivos - Betabloqueantes','Metoprolol 100 mg'],
  ['Antihipertensivos - Diureticos','Hidroclorotiazida 12.5 mg'],['Antihipertensivos - Diureticos','Hidroclorotiazida 25 mg'],
  ['Antihipertensivos - Diureticos','Indapamida 1.5 mg'],['Antihipertensivos - Diureticos','Indapamida 2.5 mg'],
  ['Antihipertensivos - Diureticos','Furosemida 20 mg'],['Antihipertensivos - Diureticos','Furosemida 40 mg'],
  ['Antihipertensivos - Diureticos','Espironolactona 25 mg'],['Antihipertensivos - Diureticos','Espironolactona 50 mg'],
  ['Antihipertensivos - Diureticos','Eplerenona 25 mg'],['Antihipertensivos - Diureticos','Eplerenona 50 mg'],
  ['Hipolipemiantes - Estatinas','Atorvastatina 10 mg'],['Hipolipemiantes - Estatinas','Atorvastatina 20 mg'],
  ['Hipolipemiantes - Estatinas','Atorvastatina 40 mg'],['Hipolipemiantes - Estatinas','Atorvastatina 80 mg'],
  ['Hipolipemiantes - Estatinas','Rosuvastatina 5 mg'],['Hipolipemiantes - Estatinas','Rosuvastatina 10 mg'],
  ['Hipolipemiantes - Estatinas','Rosuvastatina 20 mg'],['Hipolipemiantes - Estatinas','Rosuvastatina 40 mg'],
  ['Hipolipemiantes - Estatinas','Simvastatina 10 mg'],['Hipolipemiantes - Estatinas','Simvastatina 20 mg'],
  ['Hipolipemiantes - Estatinas','Simvastatina 40 mg'],
  ['Hipolipemiantes - Otros','Ezetimiba 10 mg'],['Hipolipemiantes - Otros','Ezetimiba Simvastatina 10/20 mg'],
  ['Hipolipemiantes - Otros','Ezetimiba Atorvastatina 10/20 mg'],['Hipolipemiantes - Otros','Fenofibrato 145 mg'],
  ['Hipolipemiantes - Otros','Bezafibrato 400 mg'],['Hipolipemiantes - Otros','Gemfibrozilo 600 mg'],
  ['Hipolipemiantes - Otros','Omega-3 1 g'],['Hipolipemiantes - Otros','Evolocumab 140 mg SC'],
  ['Hipolipemiantes - Otros','Alirocumab 75 mg SC'],
  ['Analgesicos / AINEs','Paracetamol 500 mg'],['Analgesicos / AINEs','Paracetamol 1000 mg'],
  ['Analgesicos / AINEs','Ibuprofeno 200 mg'],['Analgesicos / AINEs','Ibuprofeno 400 mg'],
  ['Analgesicos / AINEs','Ibuprofeno 600 mg'],['Analgesicos / AINEs','Diclofenac 50 mg'],
  ['Analgesicos / AINEs','Diclofenac 75 mg retard'],['Analgesicos / AINEs','Naproxeno 250 mg'],
  ['Analgesicos / AINEs','Naproxeno 500 mg'],['Analgesicos / AINEs','Ketorolac 10 mg'],
  ['Analgesicos / AINEs','Celecoxib 100 mg'],['Analgesicos / AINEs','Celecoxib 200 mg'],
  ['Analgesicos / AINEs','Meloxicam 7.5 mg'],['Analgesicos / AINEs','Meloxicam 15 mg'],
  ['Antibioticos','Amoxicilina 500 mg'],['Antibioticos','Amoxicilina 875 mg'],
  ['Antibioticos','Amoxicilina Clavulanico 500/125 mg'],['Antibioticos','Amoxicilina Clavulanico 875/125 mg'],
  ['Antibioticos','Azitromicina 250 mg'],['Antibioticos','Azitromicina 500 mg'],
  ['Antibioticos','Claritromicina 250 mg'],['Antibioticos','Claritromicina 500 mg'],
  ['Antibioticos','Ciprofloxacina 250 mg'],['Antibioticos','Ciprofloxacina 500 mg'],
  ['Antibioticos','Levofloxacina 250 mg'],['Antibioticos','Levofloxacina 500 mg'],
  ['Antibioticos','Trimetoprima Sulfametoxazol 80/400 mg'],['Antibioticos','Trimetoprima Sulfametoxazol 160/800 mg'],
  ['Gastrointestinal','Omeprazol 20 mg'],['Gastrointestinal','Omeprazol 40 mg'],
  ['Gastrointestinal','Pantoprazol 20 mg'],['Gastrointestinal','Pantoprazol 40 mg'],
  ['Gastrointestinal','Esomeprazol 20 mg'],['Gastrointestinal','Esomeprazol 40 mg'],
  ['Gastrointestinal','Lansoprazol 15 mg'],['Gastrointestinal','Lansoprazol 30 mg'],
  ['Gastrointestinal','Ranitidina 150 mg'],['Gastrointestinal','Metoclopramida 10 mg'],
  ['Gastrointestinal','Domperidona 10 mg'],['Gastrointestinal','Ondansetron 4 mg'],
  ['Gastrointestinal','Ondansetron 8 mg'],['Gastrointestinal','Mesalazina 400 mg'],
  ['Gastrointestinal','Loperamida 2 mg'],
  ['Vitaminas / Suplementos','Vitamina B12 1000 mcg IM'],['Vitaminas / Suplementos','Vitamina B12 500 mcg VO'],
  ['Vitaminas / Suplementos','Acido folico 1 mg'],['Vitaminas / Suplementos','Acido folico 5 mg'],
  ['Vitaminas / Suplementos','Hierro sulfato 325 mg'],['Vitaminas / Suplementos','Hierro fumarato 200 mg'],
  ['Vitaminas / Suplementos','Magnesio 250 mg'],['Vitaminas / Suplementos','Zinc 20 mg'],
  ['Vitaminas / Suplementos','Vitamina C 500 mg'],['Vitaminas / Suplementos','Vitamina C 1000 mg'],
  ['Vitaminas / Suplementos','Complejo B'],
  ['Anticoagulantes','AAS 81 mg'],['Anticoagulantes','AAS 100 mg'],
  ['Anticoagulantes','Clopidogrel 75 mg'],['Anticoagulantes','Warfarina 1 mg'],
  ['Anticoagulantes','Warfarina 2.5 mg'],['Anticoagulantes','Warfarina 5 mg'],
  ['Anticoagulantes','Rivaroxaban 10 mg'],['Anticoagulantes','Rivaroxaban 15 mg'],
  ['Anticoagulantes','Rivaroxaban 20 mg'],['Anticoagulantes','Apixaban 2.5 mg'],
  ['Anticoagulantes','Apixaban 5 mg'],['Anticoagulantes','Dabigatran 110 mg'],
  ['Anticoagulantes','Dabigatran 150 mg'],['Anticoagulantes','Enoxaparina 40 mg SC'],
  ['Anticoagulantes','Enoxaparina 60 mg SC'],
  ['Psiquiatria / Neurologia','Alprazolam 0.25 mg'],['Psiquiatria / Neurologia','Alprazolam 0.5 mg'],
  ['Psiquiatria / Neurologia','Clonazepam 0.5 mg'],['Psiquiatria / Neurologia','Clonazepam 2 mg'],
  ['Psiquiatria / Neurologia','Lorazepam 1 mg'],['Psiquiatria / Neurologia','Diazepam 5 mg'],
  ['Psiquiatria / Neurologia','Sertralina 50 mg'],['Psiquiatria / Neurologia','Sertralina 100 mg'],
  ['Psiquiatria / Neurologia','Fluoxetina 20 mg'],['Psiquiatria / Neurologia','Escitalopram 10 mg'],
  ['Psiquiatria / Neurologia','Escitalopram 20 mg'],['Psiquiatria / Neurologia','Venlafaxina 37.5 mg'],
  ['Psiquiatria / Neurologia','Venlafaxina 75 mg'],['Psiquiatria / Neurologia','Amitriptilina 25 mg'],
  ['Psiquiatria / Neurologia','Pregabalina 75 mg'],['Psiquiatria / Neurologia','Pregabalina 150 mg'],
  ['Psiquiatria / Neurologia','Gabapentina 300 mg'],['Psiquiatria / Neurologia','Melatonina 3 mg'],
  ['Psiquiatria / Neurologia','Melatonina 5 mg'],
];

const existentes = await p.$queryRaw`SELECT nombre FROM medicamentos`;
const yaExisten = new Set(existentes.map(r => r.nombre));
const nuevos = todos.filter(([,nom]) => !yaExisten.has(nom));
console.log(`Nuevos: ${nuevos.length} de ${todos.length}`);

if (nuevos.length > 0) {
  const vals = nuevos.map(([cat,nom]) => `('${nom.replace(/'/g,"''")}','${cat.replace(/'/g,"''")}') `).join(',');
  await p.$executeRawUnsafe(`INSERT INTO medicamentos (nombre,categoria) VALUES ${vals} ON CONFLICT DO NOTHING`);
  console.log('Insertados OK');
}

const total = await p.$queryRaw`SELECT COUNT(*) as n FROM medicamentos`;
console.log('Total en BD:', total[0].n.toString());
await p.$disconnect();
